# Generated by Django 3.1.4 on 2021-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='shorturl',
            field=models.CharField(max_length=25),
        ),
    ]
