# Generated by Django 3.1.4 on 2021-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0004_auto_20210102_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
